"""Fix all Folium map cells in Notebook 03."""
import json

path = r"C:\Users\owner\Downloads\Masters\Masters_Spring_2026\Advanced Deep Learning\Traffic Project 2\03_Advanced_Viz_and_Uncertainty.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# ── CELL 10: Station Map — fix 403 tile error + add legend ──
nb["cells"][10]["source"] = [
    "# == 1a: Station Location Map (Traffic + Weather) ==\n",
    "# FIX: CartoDB Voyager tiles (OpenStreetMap blocks requests without referer)\n",
    "from branca.element import Template, MacroElement\n",
    "\n",
    "ct_center = [41.6, -72.7]\n",
    "m1 = folium.Map(\n",
    "    location=ct_center, zoom_start=9,\n",
    "    tiles='https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',\n",
    '    attr=\'&copy; <a href="https://carto.com/">CARTO</a> &copy; <a href="https://www.openstreetmap.org/copyright">OSM</a>\'\n',
    ")\n",
    "\n",
    "# Traffic stations (blue circles, sized by avg volume)\n",
    "for _, row in station_map.iterrows():\n",
    "    avg_traffic = df[df['station_id'] == row['station_id']]['traffic_count'].mean()\n",
    "    folium.CircleMarker(\n",
    "        location=[row['latitude'], row['longitude']],\n",
    "        radius=max(4, min(15, avg_traffic / 500)),\n",
    "        color='blue', fill=True, fill_opacity=0.6,\n",
    "        popup=folium.Popup(\n",
    '            f"<b>Traffic Station: {row[\'station_id\']}</b><br>"\n',
    '            f"Avg Traffic: {avg_traffic:.0f} veh/hr<br>"\n',
    '            f"Lat: {row[\'latitude\']:.4f}, Lon: {row[\'longitude\']:.4f}",\n',
    "            max_width=250\n",
    "        ),\n",
    "        tooltip=f\"Station {row['station_id']}\"\n",
    "    ).add_to(m1)\n",
    "\n",
    "# Weather stations (red markers)\n",
    "try:\n",
    "    import requests as req\n",
    '    resp = req.get("https://mesonet.agron.iastate.edu/geojson/network/CT_ASOS.geojson", timeout=15)\n',
    "    gj = resp.json()\n",
    "    for feat in gj['features']:\n",
    "        props = feat['properties']\n",
    "        sid = props.get('sid', props.get('id', ''))\n",
    "        coords = feat['geometry']['coordinates']\n",
    "        sname = props.get('sname', '')\n",
    "        folium.Marker(\n",
    "            location=[coords[1], coords[0]],\n",
    "            icon=folium.Icon(color='red', icon='cloud'),\n",
    '            popup=f"<b>ASOS: {sid}</b><br>{sname}",\n',
    '            tooltip=f"Weather: {sid}"\n',
    "        ).add_to(m1)\n",
    "except:\n",
    '    print("Could not fetch ASOS station coords.")\n',
    "\n",
    "# == Legend ==\n",
    "legend_html = '''\n",
    "{% macro html(this, kwargs) %}\n",
    '<div style="position:fixed; bottom:30px; left:30px; z-index:1000;\n',
    "     background:white; padding:12px 16px; border-radius:8px;\n",
    "     border:2px solid #555; font-size:13px; font-family:Arial;\n",
    '     box-shadow: 2px 2px 6px rgba(0,0,0,0.3);">\n',
    '  <b style="font-size:15px;">CT Station Map (2024)</b><br><br>\n',
    '  <svg width="14" height="14"><circle cx="7" cy="7" r="6" fill="blue" opacity="0.6"/></svg>\n',
    "  &nbsp;Traffic Station (FHWA TMAS)<br>\n",
    '  <span style="font-size:11px; color:gray; margin-left:20px;">Circle size = avg hourly volume</span><br><br>\n',
    '  <svg width="14" height="14"><polygon points="7,1 13,13 1,13" fill="red"/></svg>\n',
    "  &nbsp;Weather Station (ASOS)<br>\n",
    '  <hr style="margin:6px 0;">\n',
    '  <span style="font-size:11px; color:#555;">Data: FHWA TMAS + Iowa State Mesonet</span>\n',
    "</div>\n",
    "{% endmacro %}\n",
    "'''\n",
    "legend = MacroElement()\n",
    "legend._template = Template(legend_html)\n",
    "m1.get_root().add_child(legend)\n",
    "\n",
    "m1.save(str(PROCESSED / 'map_station_locations.html'))\n",
    'print("Saved: map_station_locations.html")\n',
    "\n",
    "from IPython.display import HTML\n",
    "HTML(m1._repr_html_())\n",
]

# ── CELL 11: Traffic Heatmap — add title + legend ──
nb["cells"][11]["source"] = [
    "# == 1b: Traffic Volume Heatmap ==\n",
    "# Shows AVERAGE HOURLY traffic volume per station across all of 2024\n",
    "from branca.element import Template, MacroElement\n",
    "\n",
    "m2 = folium.Map(location=ct_center, zoom_start=9, tiles='CartoDB dark_matter')\n",
    "\n",
    "# Compute average traffic per station\n",
    "heat_data = []\n",
    "station_stats = []\n",
    "for _, row in station_map.iterrows():\n",
    "    avg_vol = df[df['station_id'] == row['station_id']]['traffic_count'].mean()\n",
    "    if not np.isnan(avg_vol):\n",
    "        heat_data.append([row['latitude'], row['longitude'], avg_vol])\n",
    "        station_stats.append(avg_vol)\n",
    "\n",
    "HeatMap(\n",
    "    heat_data,\n",
    "    min_opacity=0.4,\n",
    "    max_zoom=13,\n",
    "    radius=25,\n",
    "    blur=15,\n",
    "    gradient={0.4: 'blue', 0.65: 'lime', 0.8: 'yellow', 1: 'red'}\n",
    ").add_to(m2)\n",
    "\n",
    "# == Title + Legend ==\n",
    "min_stat = f'{min(station_stats):.0f}'\n",
    "max_stat = f'{max(station_stats):.0f}'\n",
    "\n",
    "title_legend = '''\n",
    "{% macro html(this, kwargs) %}\n",
    '<div style="position:fixed; top:15px; left:50%%; transform:translateX(-50%%); z-index:1000;\n',
    "     background:rgba(0,0,0,0.85); padding:10px 24px; border-radius:8px;\n",
    '     font-family:Arial; text-align:center; box-shadow:2px 2px 6px rgba(0,0,0,0.5);">\n',
    '  <span style="color:white; font-size:18px; font-weight:bold;">\n',
    "    Average Hourly Traffic Volume &mdash; Connecticut 2024\n",
    "  </span><br>\n",
    '  <span style="color:#ccc; font-size:12px;">\n',
    "    Each point = one FHWA TMAS station &bull; Color intensity = avg vehicles/hour\n",
    "  </span>\n",
    "</div>\n",
    '<div style="position:fixed; bottom:30px; left:30px; z-index:1000;\n',
    "     background:rgba(0,0,0,0.85); padding:12px 16px; border-radius:8px;\n",
    '     font-size:13px; font-family:Arial; color:white; box-shadow:2px 2px 6px rgba(0,0,0,0.5);">\n',
    "  <b>Volume Legend</b><br><br>\n",
    '  <div style="display:flex; align-items:center; gap:4px;">\n',
    '    <div style="width:140px; height:14px; border-radius:3px;\n',
    '         background:linear-gradient(to right, blue, lime, yellow, red);"></div>\n',
    "  </div>\n",
    '  <div style="display:flex; justify-content:space-between; width:140px; font-size:11px; margin-top:2px;">\n',
    "    <span>Low</span><span>Med</span><span>High</span>\n",
    "  </div><br>\n",
    '  <span style="font-size:11px; color:#aaa;">\n',
    "''' + f'    Range: {min_stat} &ndash; {max_stat} vehicles/hour\\n' + '''",
    "  </span>\n",
    "</div>\n",
    "{% endmacro %}\n",
    "'''\n",
    "\n",
    "legend2 = MacroElement()\n",
    "legend2._template = Template(title_legend)\n",
    "m2.get_root().add_child(legend2)\n",
    "\n",
    "m2.save(str(PROCESSED / 'map_traffic_heatmap.html'))\n",
    'print("Saved: map_traffic_heatmap.html")\n',
    "print(f'Volume range: {min(station_stats):.0f} - {max(station_stats):.0f} veh/hr')\n",
    "\n",
    "from IPython.display import HTML\n",
    "HTML(m2._repr_html_())\n",
]

# ── CELL 12: Graph Edges — fix tiles ──
nb["cells"][12]["source"] = [
    "# == 1c: Graph Edges Map (KNN adjacency) ==\n",
    "m3 = folium.Map(\n",
    "    location=ct_center, zoom_start=9,\n",
    "    tiles='https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',\n",
    "    attr='&copy; CARTO &copy; OSM'\n",
    ")\n",
    "\n",
    "coords_list = station_map[['latitude', 'longitude']].values\n",
    "n_nodes = len(coords_list)\n",
    "\n",
    "# Draw edges\n",
    "for i in range(n_nodes):\n",
    "    for j in range(i+1, n_nodes):\n",
    "        if adj_matrix[i, j] > 0:\n",
    "            weight = adj_matrix[i, j]\n",
    "            folium.PolyLine(\n",
    "                locations=[\n",
    "                    [coords_list[i, 0], coords_list[i, 1]],\n",
    "                    [coords_list[j, 0], coords_list[j, 1]]\n",
    "                ],\n",
    "                color='red',\n",
    "                weight=max(1, weight * 4),\n",
    "                opacity=0.5,\n",
    "                tooltip=f'Edge weight: {weight:.3f}'\n",
    "            ).add_to(m3)\n",
    "\n",
    "# Draw nodes\n",
    "for _, row in station_map.iterrows():\n",
    "    folium.CircleMarker(\n",
    "        location=[row['latitude'], row['longitude']],\n",
    "        radius=6, color='navy', fill=True, fill_opacity=0.8,\n",
    "        popup=f\"Node {row['node_idx']}: {row['station_id']}\"\n",
    "    ).add_to(m3)\n",
    "\n",
    "m3.save(str(PROCESSED / 'map_graph_edges.html'))\n",
    'print("Saved: map_graph_edges.html")\n',
    "\n",
    "from IPython.display import HTML\n",
    "HTML(m3._repr_html_())\n",
]

# ── CELL 13: Hourly Animation — normalize weights + fix stagnant ──
nb["cells"][13]["source"] = [
    "# == 1d: Hourly Traffic Animation (HeatMapWithTime) ==\n",
    "# FIX: Normalize weights to [0,1] so frames actually differ visually\n",
    "from branca.element import Template, MacroElement\n",
    "\n",
    "m4 = folium.Map(location=ct_center, zoom_start=9, tiles='CartoDB positron')\n",
    "\n",
    "# Compute hourly averages per station\n",
    "hourly_frames = []\n",
    "all_vals = []  # for global normalization\n",
    "\n",
    "for hour in range(24):\n",
    "    frame_data = []\n",
    "    for _, row in station_map.iterrows():\n",
    "        mask = (df['station_id'] == row['station_id']) & (df['timestamp'].dt.hour == hour)\n",
    "        avg_vol = df.loc[mask, 'traffic_count'].mean()\n",
    "        if not np.isnan(avg_vol) and avg_vol > 0:\n",
    "            frame_data.append([row['latitude'], row['longitude'], avg_vol])\n",
    "            all_vals.append(avg_vol)\n",
    "    hourly_frames.append(frame_data)\n",
    "\n",
    "# Normalize all weights to [0, 1] using global min/max\n",
    "global_min = min(all_vals) if all_vals else 0\n",
    "global_max = max(all_vals) if all_vals else 1\n",
    "global_range = global_max - global_min if global_max > global_min else 1\n",
    "\n",
    "hourly_frames_norm = []\n",
    "for frame in hourly_frames:\n",
    "    norm_frame = []\n",
    "    for lat, lon, val in frame:\n",
    "        norm_val = (val - global_min) / global_range\n",
    "        norm_frame.append([lat, lon, norm_val])\n",
    "    hourly_frames_norm.append(norm_frame)\n",
    "\n",
    "HeatMapWithTime(\n",
    "    hourly_frames_norm,\n",
    "    index=[f'{h:02d}:00' for h in range(24)],\n",
    "    auto_play=True,\n",
    "    speed_step=0.5,\n",
    "    max_opacity=0.8,\n",
    "    radius=30,\n",
    "    min_opacity=0.1,\n",
    "    use_local_extrema=False,  # use global scale so frames are comparable\n",
    "    gradient={0.2: 'blue', 0.4: 'cyan', 0.6: 'lime', 0.8: 'yellow', 1.0: 'red'}\n",
    ").add_to(m4)\n",
    "\n",
    "# == Title ==\n",
    "title_html4 = '''\n",
    "{% macro html(this, kwargs) %}\n",
    '<div style="position:fixed; top:15px; left:50%%; transform:translateX(-50%%);\n',
    "     z-index:1000; background:white; padding:10px 24px; border-radius:8px;\n",
    '     border:2px solid #333; font-family:Arial; text-align:center;\n',
    '     box-shadow:2px 2px 6px rgba(0,0,0,0.3);">\n',
    '  <b style="font-size:16px;">Hourly Traffic Volume Animation &mdash; CT 2024</b><br>\n',
    '  <span style="font-size:12px; color:#555;">\n',
    "    Use the slider or play button below to see traffic shift across 24 hours\n",
    "  </span>\n",
    "</div>\n",
    "{% endmacro %}\n",
    "'''\n",
    "title4 = MacroElement()\n",
    "title4._template = Template(title_html4)\n",
    "m4.get_root().add_child(title4)\n",
    "\n",
    "m4.save(str(PROCESSED / 'map_hourly_traffic_animation.html'))\n",
    'print("Saved: map_hourly_traffic_animation.html")\n',
    "print(f'Global traffic range: {global_min:.0f} - {global_max:.0f} veh/hr')\n",
    "print(f'Frames: {len(hourly_frames_norm)}, Points per frame: {[len(f) for f in hourly_frames_norm]}')\n",
    "\n",
    "from IPython.display import HTML\n",
    "HTML(m4._repr_html_())\n",
]

# ── CELL 40: Spatial Error Map — fix tiles ──
nb["cells"][40]["source"] = [
    "# == Folium Spatial Error Map ==\n",
    "m5 = folium.Map(\n",
    "    location=ct_center, zoom_start=9,\n",
    "    tiles='https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',\n",
    "    attr='&copy; CARTO &copy; OSM'\n",
    ")\n",
    "\n",
    "max_mae = error_df['mae'].max()\n",
    "for _, row in error_df.iterrows():\n",
    "    norm_err = row['mae'] / max_mae\n",
    "    r = int(255 * norm_err)\n",
    "    g = int(255 * (1 - norm_err))\n",
    "    color = f'#{r:02x}{g:02x}00'\n",
    "\n",
    "    folium.CircleMarker(\n",
    "        location=[row['latitude'], row['longitude']],\n",
    "        radius=max(5, norm_err * 20),\n",
    "        color=color, fill=True, fill_color=color, fill_opacity=0.7,\n",
    "        popup=folium.Popup(\n",
    '            f"<b>Station: {row[\'station_id\']}</b><br>"\n',
    '            f"LSTM MAE: {row[\'mae\']:.1f} veh/hr",\n',
    "            max_width=200\n",
    "        ),\n",
    "        tooltip=f\"{row['station_id']}: MAE={row['mae']:.0f}\"\n",
    "    ).add_to(m5)\n",
    "\n",
    "m5.save(str(PROCESSED / 'map_spatial_error.html'))\n",
    'print("Saved: map_spatial_error.html")\n',
    "\n",
    "from IPython.display import HTML\n",
    "HTML(m5._repr_html_())\n",
]

with open(path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("All 5 Folium cells fixed successfully!")
print("  Cell 10: Station map -> CartoDB Voyager tiles + legend")
print("  Cell 11: Traffic heatmap -> title + volume legend with range")
print("  Cell 12: Graph edges -> CartoDB Voyager tiles")
print("  Cell 13: Hourly animation -> normalized weights + title")
print("  Cell 40: Spatial error -> CartoDB Light tiles")
